package command.exceptions;
/**
 * Исключение, вызываемое при ошибке выполнения команды из-за внутренних программных причин
 */
public class FailedCommandExecutionException extends Exception {
}
